server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

  client:
    register-with-eureka: false
    fetch-registry: false
