server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

  application:
    name: storage-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
