server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate

